// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: certificate.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/1f349/orchid/database/types"
	"github.com/gobuffalo/nulls"
)

const addCertificate = `-- name: AddCertificate :execlastid
INSERT INTO certificates (name, auto_renew, active, dns, not_after, updated_at, authority, common_name, country, org,
                          org_unit, locality, province)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddCertificateParams struct {
	Name       string          `json:"name"`
	AutoRenew  bool            `json:"auto_renew"`
	Active     bool            `json:"active"`
	Dns        nulls.Int64     `json:"dns"`
	NotAfter   nulls.Time      `json:"not_after"`
	UpdatedAt  time.Time       `json:"updated_at"`
	Authority  types.Authority `json:"authority"`
	CommonName string          `json:"common_name"`
	Country    string          `json:"country"`
	Org        string          `json:"org"`
	OrgUnit    string          `json:"org_unit"`
	Locality   string          `json:"locality"`
	Province   string          `json:"province"`
}

func (q *Queries) AddCertificate(ctx context.Context, arg AddCertificateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addCertificate,
		arg.Name,
		arg.AutoRenew,
		arg.Active,
		arg.Dns,
		arg.NotAfter,
		arg.UpdatedAt,
		arg.Authority,
		arg.CommonName,
		arg.Country,
		arg.Org,
		arg.OrgUnit,
		arg.Locality,
		arg.Province,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const addCertificateOwner = `-- name: AddCertificateOwner :exec
INSERT INTO owners (owner, cert_id)
VALUES (?, ?)
`

type AddCertificateOwnerParams struct {
	Owner  string `json:"owner"`
	CertID int64  `json:"cert_id"`
}

func (q *Queries) AddCertificateOwner(ctx context.Context, arg AddCertificateOwnerParams) error {
	_, err := q.db.ExecContext(ctx, addCertificateOwner, arg.Owner, arg.CertID)
	return err
}

const changeCertificateDetails = `-- name: ChangeCertificateDetails :exec
UPDATE certificates
SET country            = ?,
    org                = ?,
    org_unit           = ?,
    locality           = ?,
    province           = ?,
    details_updated_at = DATETIME()
WHERE id = ?
`

type ChangeCertificateDetailsParams struct {
	Country  string `json:"country"`
	Org      string `json:"org"`
	OrgUnit  string `json:"org_unit"`
	Locality string `json:"locality"`
	Province string `json:"province"`
	ID       int64  `json:"id"`
}

func (q *Queries) ChangeCertificateDetails(ctx context.Context, arg ChangeCertificateDetailsParams) error {
	_, err := q.db.ExecContext(ctx, changeCertificateDetails,
		arg.Country,
		arg.Org,
		arg.OrgUnit,
		arg.Locality,
		arg.Province,
		arg.ID,
	)
	return err
}

const checkCertOwner = `-- name: CheckCertOwner :one
SELECT cert.id
FROM certificates AS cert
         INNER JOIN owners ON owners.cert_id = cert.id
WHERE cert.active = 1
  AND cert.id = ?
  AND owners.owner = ?
LIMIT 1
`

type CheckCertOwnerParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) CheckCertOwner(ctx context.Context, arg CheckCertOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCertOwner, arg.ID, arg.Owner)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findNextCert = `-- name: FindNextCert :one
SELECT cert.id, cert.not_after, cert.common_name
FROM certificates AS cert
WHERE cert.active = 1
  AND (cert.auto_renew = 1 OR cert.not_after IS NULL)
  AND cert.renewing = 0
  AND (cert.renew_retry IS NULL OR DATETIME() > DATETIME(cert.renew_retry))
  AND (cert.not_after IS NULL OR DATETIME(cert.not_after, 'utc', '-30 days') < DATETIME())
ORDER BY cert.not_after DESC NULLS FIRST
LIMIT 1
`

type FindNextCertRow struct {
	ID         int64      `json:"id"`
	NotAfter   nulls.Time `json:"not_after"`
	CommonName string     `json:"common_name"`
}

func (q *Queries) FindNextCert(ctx context.Context) (FindNextCertRow, error) {
	row := q.db.QueryRowContext(ctx, findNextCert)
	var i FindNextCertRow
	err := row.Scan(&i.ID, &i.NotAfter, &i.CommonName)
	return i, err
}

const findOwnedCerts = `-- name: FindOwnedCerts :many
SELECT cert.id,
       cert.name,
       cert.authority,
       cert.auto_renew,
       cert.active,
       cert.renewing,
       cert.renew_retry,
       cert.not_after,
       cert.updated_at,
       cert.common_name,
       cert.country,
       cert.org,
       cert.org_unit,
       cert.locality,
       cert.province,
       certificate_domains.domain
FROM certificates AS cert
         LEFT JOIN certificate_domains ON cert.id = certificate_domains.cert_id
         INNER JOIN owners ON owners.cert_id = cert.id
WHERE owners.owner = ?
`

type FindOwnedCertsRow struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Authority  types.Authority `json:"authority"`
	AutoRenew  bool            `json:"auto_renew"`
	Active     bool            `json:"active"`
	Renewing   bool            `json:"renewing"`
	RenewRetry nulls.Time      `json:"renew_retry"`
	NotAfter   nulls.Time      `json:"not_after"`
	UpdatedAt  time.Time       `json:"updated_at"`
	CommonName string          `json:"common_name"`
	Country    string          `json:"country"`
	Org        string          `json:"org"`
	OrgUnit    string          `json:"org_unit"`
	Locality   string          `json:"locality"`
	Province   string          `json:"province"`
	Domain     sql.NullString  `json:"domain"`
}

func (q *Queries) FindOwnedCerts(ctx context.Context, owner string) ([]FindOwnedCertsRow, error) {
	rows, err := q.db.QueryContext(ctx, findOwnedCerts, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOwnedCertsRow
	for rows.Next() {
		var i FindOwnedCertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Authority,
			&i.AutoRenew,
			&i.Active,
			&i.Renewing,
			&i.RenewRetry,
			&i.NotAfter,
			&i.UpdatedAt,
			&i.CommonName,
			&i.Country,
			&i.Org,
			&i.OrgUnit,
			&i.Locality,
			&i.Province,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCertificate = `-- name: RemoveCertificate :exec
UPDATE certificates
SET active = 0
WHERE id = ?
`

func (q *Queries) RemoveCertificate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCertificate, id)
	return err
}

const setCertificateAutoRenew = `-- name: SetCertificateAutoRenew :exec
UPDATE certificates
SET auto_renew = ?
WHERE id = ?
`

type SetCertificateAutoRenewParams struct {
	AutoRenew bool  `json:"auto_renew"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetCertificateAutoRenew(ctx context.Context, arg SetCertificateAutoRenewParams) error {
	_, err := q.db.ExecContext(ctx, setCertificateAutoRenew, arg.AutoRenew, arg.ID)
	return err
}

const setRetryFlag = `-- name: SetRetryFlag :exec
UPDATE certificates
SET renew_retry = DATETIME('now', '+1 day')
WHERE id = ?
`

func (q *Queries) SetRetryFlag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setRetryFlag, id)
	return err
}

const triggerManualRenew = `-- name: TriggerManualRenew :exec
UPDATE certificates
SET renew_retry = DATETIME('now'),
    not_after   = NULL
WHERE id = ?
`

func (q *Queries) TriggerManualRenew(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, triggerManualRenew, id)
	return err
}

const updateCertAfterRenewal = `-- name: UpdateCertAfterRenewal :exec
UPDATE certificates
SET renewing    = 0,
    renew_retry = 0,
    not_after   = ?,
    updated_at  = ?
WHERE id = ?
`

type UpdateCertAfterRenewalParams struct {
	NotAfter  nulls.Time `json:"not_after"`
	UpdatedAt time.Time  `json:"updated_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateCertAfterRenewal(ctx context.Context, arg UpdateCertAfterRenewalParams) error {
	_, err := q.db.ExecContext(ctx, updateCertAfterRenewal, arg.NotAfter, arg.UpdatedAt, arg.ID)
	return err
}

const updateRenewingState = `-- name: UpdateRenewingState :exec
UPDATE certificates
SET renewing    = ?,
    renew_retry = ?
WHERE id = ?
`

type UpdateRenewingStateParams struct {
	Renewing   bool       `json:"renewing"`
	RenewRetry nulls.Time `json:"renew_retry"`
	ID         int64      `json:"id"`
}

func (q *Queries) UpdateRenewingState(ctx context.Context, arg UpdateRenewingStateParams) error {
	_, err := q.db.ExecContext(ctx, updateRenewingState, arg.Renewing, arg.RenewRetry, arg.ID)
	return err
}
