// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: domain_acme_tokens.sql

package database

import (
	"context"
)

const findDomainAcmeToken = `-- name: FindDomainAcmeToken :many
SELECT id, domain, source, token FROM dns_api_tokens WHERE domain LIKE CONCAT('%', CAST(? AS TEXT))
`

func (q *Queries) FindDomainAcmeToken(ctx context.Context, dollar_1 string) ([]DnsApiToken, error) {
	rows, err := q.db.QueryContext(ctx, findDomainAcmeToken, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsApiToken
	for rows.Next() {
		var i DnsApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Source,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
